spring:
  application:
    name: JAI-Doc
  config:
    import:
      - configurations/actuator-configuration.yml
      - configurations/documentation-configuration.yml
      - configurations/logging-configuration.yml
      - configurations/mcp-configuration.yml
      - configurations/springdoc-configuration.yml
  threads:
    virtual:
      enabled: true
