spring:
  application:
    name: JAIDoc
  config:
    import:
      - configurations/actuator-configuration.yml
      - configurations/db-configuration.yml
      - configurations/documentation-configuration.yml
      - configurations/logging-configuration.yml
      - configurations/mcp-configuration.yml
      - configurations/springdoc-configuration.yml
  threads:
    virtual:
      enabled: true
