spring:
  ai:
    embedding:
      transformer:
        onnx:
          model-uri: ${AI_TRANSFORMER_ONNX:file:./onnx/model_qint8_avx512_vnni.onnx}
        tokenizer:
          uri: ${AI_TRANSFORMER_TOKENIZER:file:./onnx/tokenizer.json}
