spring:
  ai:
    mcp:
      server:
        enabled: true
        name: ${spring.application.name}
        version: @project.version@
        protocol: streamable
        stdio: ${MCP_SERVER_STDIO:false}
        request-timeout: ${MCP_SERVER_TIMEOUT:20S}
