spring:
  jpa:
    properties:
      hibernate.search.backend.lucene.directory-type: local-filesystem
      hibernate.search.backend.lucene.directory.root: ${SEARCH_INDEX_DIR:./jaidoc-index}
      hibernate.search.default.indexing.plan.synchronization: sync
